chatPdf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('accounts/', include('allauth.urls')),
]

dashboard/urls.py
from django.urls import path
from .views import home, chatbot, projects, upcoming_tools, billing, faq, contact, notifications, settings, profile, \
    terms, privacy, process_message, process_document_view, payment, notifications_details

app_name = 'dashboard'
urlpatterns = [
    path('home/', home, name='home'),
    path('chat/', chatbot, name='chat'),
    path('projects/', projects, name='projects'),
    path('upcoming-tools/', upcoming_tools, name='upcoming'),
    path('billing/', billing, name='billing'),
    path('faq', faq, name='faq'),
    path('contact/', contact, name='contact'),
    path('notifications', notifications, name='notifications'),
    path('settings/', settings, name='setttings'),
    path('profile', profile, name='profile'),
    path('terms', terms, name='terms'),
    path('privacy', privacy, name='privacy'),
    path('process-message', process_message, name='process-message'),
    path('process-document', process_document_view, name='process-document'),
    path('receivepayment/', payment, name='payment'),
    path('notification-details/<int:id>', notifications_details, name='notfication_details'),

]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
import json


class Notification(models.Model):
    message = models.CharField(max_length=255)
    details = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)
    user = models.ManyToManyField(User)

    def __str__(self):
        return self.message


class TokenTracker(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    token_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"Token count for {self.user.username}"


class PdfChat(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=300, default=None)
    vector_database = models.JSONField()
    answer_array = models.TextField()

    def set_vector_database(self, obj):
        self.vector_database = json.dumps(obj)

    def get_vector_database(self):
        return json.loads(self.vector_database)

    def set_answer_array(self, answer_array):
        self.answer_array = json.dumps(self.answer_array)

    def get_answer_array(self):
        return json.loads(self.answer_array)


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField()
    phone = models.TextField()
    message = models.TextField(default=None)

    def __str__(self):
        return self.email

dashboard/views.py
import time
import os
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from dashboard.models import TokenTracker, Notification
from core.calc_tokens import get_tokens
from core import chatpdf
from django.http import JsonResponse, HttpResponse
import json
from django.views.decorators.csrf import csrf_exempt
from rave_python import Rave, RaveExceptions, Misc
from .models import Message
import json
from dotenv import load_dotenv
from django.views.decorators.http import require_POST

# Load environment variables
load_dotenv()

rave = Rave(os.getenv('RAVE_PUBLIC_KEY'), os.getenv('RAVE_SECRET_KEY'),
            usingEnv=True)



@login_required
def home(request):
    user_count = User.objects.count()

    context = {'user_count': user_count}
    return render(request, 'index-2.html', context)


@login_required
def chatbot(request):
    user = request.user
    token_tracker, created = TokenTracker.objects.get_or_create(user=user)
    token_tracker.save()

    context = {}

    return render(request, 'ai-chat-bot.html', context)


@login_required
def projects(request):
    context = {}

    return render(request, 'projects.html', context)


@login_required
def upcoming_tools(request):
    context = {}
    return render(request, 'upcoming-tools.html', context)


@login_required
def billing(request):
    if request.method == "POST":
        amount = int(request.POST['amount'])
        number = request.POST['number']
        email = request.POST['email']

        if amount >= 2000:

            # mobile payload
            payload = {
                "amount": amount,
                "email": email,
                "phonenumber": number,
                "redirect_url": "http://127.0.0.1:8000/receivepayment",
                "IP": ""
            }

            try:
                res = rave.UGMobile.charge(payload)

                if res['status'] == 'success':
                    print("HEHEHEHEHHEHEHEH")
                    return redirect(res['link'])


            except RaveExceptions.TransactionChargeError as e:
                print(e.err)
                print(e.err["flwRef"])

            except RaveExceptions.TransactionVerificationError as e:
                print(e.err["errMsg"])
                print(e.err["txRef"])
    context = {}
    return render(request, 'user-billing.html', context)


@login_required
def faq(request):
    context = {}
    return render(request, 'faq.html', context)


@login_required
def contact(request):
    context = {}
    if request.method == "POST":
        email = request.POST['email']
        message = request.POST['message']
        phone = request.POST['phone']
        con = Message.objects.create(user=request.user, email=email, phone=phone, message=message)

        con.save()

        return render(request, 'contact.html', context)

        # Give the user a message so that they can see that it is successful

    context = {}
    return render(request, 'contact.html', context)


@login_required
def notifications(request):
    nofts = Notification.objects.filter(user=request.user)
    context = {'notifications':nofts}
    return render(request, 'notifications.html', context)

@login_required
def notifications_details(request,id):
    nofts = Notification.objects.filter(id=id)
    context = {'notification':nofts[0]}
    return render(request, 'notification-single.html', context)

@login_required
def settings(request):
    context = {}

    if request.method == "POST":
        if request.POST.get('fname', None):
            fname = request.POST.get('fname', None)
            lname = request.POST.get('lname', None)
            username = request.POST.get('username', None)
            email = request.POST.get('email', None)

            user = request.user
            user.first_name = fname
            user.last_name = lname
            user.username = username
            user.email = email
            user.save()
            return redirect('/profile')
    return render(request, 'user-settings.html', context)


@login_required
def profile(request):
    context = {}
    return render(request, 'user-profile.html', context)


@login_required
def terms(request):
    context = {}
    return render(request, 'terms.html', context)


@login_required
def privacy(request):
    context = {}
    return render(request, 'privacy.html', context)


@login_required
@csrf_exempt
def process_message(request):
    if request.method == 'POST':
        print("##################")
        print(request.POST)
        try:
            request_data = json.loads(request.body.decode('utf-8'))
            user_message = request_data.get('userMessage', '')
        except json.JSONDecodeError:
            return JsonResponse({'error': 'Invalid JSON in the request'}, status=400)

        bot_response = chatpdf.process_prompt(user_message, request)
        data = {
            "botResponse": bot_response
        }

        json.dumps(data)

        return JsonResponse(data, status=200)


@login_required()
@csrf_exempt
def process_document_view(request):
    if request.method == 'POST':
        # Check if a file was uploaded
        if 'file' not in request.FILES:
            return JsonResponse({
                "botResponse": "It seems like the file was not uploaded correctly, can you try "
                               "again. If the problem persists, try using a different file"
            }, status=400)

        uploaded_file = request.FILES['file']
        file_path = f'Media/{uploaded_file.name}'

        # Save the file
        with open(file_path, 'wb+') as destination:
            for chunk in uploaded_file.chunks():
                destination.write(chunk)

        # Process the document using the worker module (assuming 'worker' is properly imported)
        chatpdf.process_document(file_path, request, uploaded_file.name)

        # Return a success message as JSON
        return JsonResponse({
            "botResponse": "Thank you for providing your PDF document. I have analyzed it, so now you can ask me any "
                           "questions regarding it!"
        }, status=200)


@login_required
def payment(request):
    if request.method == 'GET':

        resp = request.GET['resp']
        print("xxxxxxxxxxxxxxxxxxxxxxx")
        print(resp)
        resp = json.loads(resp)
        state = resp['status']
        if state == 'success':
            amount = resp['data']['charged_amount']
            # Create the token object
            persons_tokens = TokenTracker.objects.get_or_create(user=request.user)[0]
            persons_tokens.token_count = persons_tokens.token_count + int((int(amount) / 2000) * 1000)
            persons_tokens.save()
            # Add the tokens to the person
            return redirect('/home/')

    return HttpResponse("Hello")

dashboard/templates/ai-chat-bot.html
{% extends 'base.html' %}
{% load static %}
{% block title %}My Page{% endblock %}
{% block css %}
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
            integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
            crossorigin="anonymous"
    />
        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
 <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>
{% endblock %}
{% block content %}

    <div class="container d-flex flex-column vh-100">
        <div class="row">
            <div class="col-12" style="margin-top: 2rem">
                <h1 class="text-center mb-3">Chat pdf</h1>
            </div>
            <div class="col-12 text-center">
                <div class="custom-control custom-switch mb-3">
                    <input type="checkbox" class="custom-control-input" id="light-dark-mode-switch"/>
                    <label class="custom-control-label" for="light-dark-mode-switch">Toggle light/dark mode</label>
                </div>
            </div>
        </div>
        <div class="row flex-grow-1 overflow-auto">
            <div class="col-12 col-md-8 mx-auto d-flex flex-column">
                <div id="chat-window" class="p-3">
                    <div id="message-list"></div>
                    <div class="loading-animation my-loading">
                        <div class="loading-dots my-loading">
                            <div class="dot"></div>
                            <div class="dot"></div>
                            <div class="dot"></div>
                        </div>
                    </div>
                    <div class="loading-animation">
                        <div class="loading-dots">
                            <div class="dot"></div>
                            <div class="dot"></div>
                            <div class="dot"></div>
                        </div>
                    </div>
                </div>
                <div class="input-group mt-1">
                    <input type="text" id="message-input" class="form-control" placeholder="Type your message here..."/>
                    <div class="input-group-append">
                        <button id="send-button" class="btn btn-primary send">
                            <i class='fa fa-paper-plane'></i>
                        </button>
                        <button id="reset-button" class="btn btn-primary reset">
                            <i class="fa fa-refresh"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block script %}
<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
    <script>
        const csrf_token = document.querySelector('input[name=csrfmiddlewaretoken]').value;
    </script>
{% endblock %}

dashboard/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Contact{% endblock %}

{% block content %}
<!-- FAQ Page -->
<div class="chatPdf_fn_contact_page">

    <!-- Page Title -->
    <div class="chatPdf_fn_pagetitle">
        <h2 class="title">Contact Us</h2>
    </div>
    <!-- !Page Title -->

    <div class="contactpage">
        <div class="container small">

            <p>We value your feedback, inquiries, and suggestions. Please feel free to reach out to us using the contact
                form below. Our dedicated team is ready to assist you with any questions or concerns you may have.</p>
            <p>Please fill out the form with your contact information and a detailed message, and we will get back to
                you as soon as possible. Your privacy is important to us, and we will never share your information with
                third parties.</p>

            <div class="fn_contact_form">
                <form  method="post" class="contact_form"
                      autocomplete="off">
                    {% csrf_token %}
                    <div class="input_list">
                        <ul>
                            <li>
                                <input id="name" type="text" placeholder="Full Name *" name="firstname"/>
                            </li>
                            <li>
                                <input id="email" type="text" placeholder="Email *" name = 'email'/>
                            </li>
                            <li>
                                <input id="tel" type="text" placeholder="Phone" name="phone"/>
                            </li>
                            <li>
                                <textarea id="message" placeholder="Your Message *" name = 'message'></textarea>
                            </li>
                            <li>
                                <div>
                                    <button type="submit"  class="chatPdf_fn_button">
                                        <span>Send Message</span>
                                    </button>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="returnmessage"
                         data-success="Your message has been received, We will contact you soon."></div>
                    <div class="empty_notice"><span>! Please Fill Required Fields !</span></div>
                </form>
            </div>
            <div class="fn__space__30"></div>

            <hr data-h="2">
            <div class="fn__space__10"></div>
            <p>In case you prefer to contact us through other means, you can also find our phone number and mailing
                address listed below. We strive to provide exceptional customer service and ensure that your experience
                with us is seamless.</p>
            <p>Thank you for choosing us as your trusted resource. We look forward to hearing from you!</p>
            <p>Contact Information:<br>
                Phone: <span class="heading_color">[Insert Phone Number]</span><br>
                Address: <span class="heading_color">[Insert Mailing Address]</span></p>
            <p>Please note that our office hours are [Insert Office Hours]. While we endeavor to respond to all
                inquiries promptly, there may be slight delays during weekends and holidays.</p>

        </div>
    </div>


</div>
<!-- !FAQ Page -->

{% endblock %}

dashboard/templates/faq.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Projects{% endblock %}

{% block content %}
<!-- FAQ Page -->
<div class="chatPdf_fn_faq_page">

    <!-- Page Title -->
    <div class="chatPdf_fn_pagetitle">
        <h2 class="title">Frequently Asked Questions</h2>
    </div>
    <!-- !Page Title -->

    <div class="faq">
        <div class="container small">

            <!-- Accordion Shortcode -->
            <div class="chatPdf_fn_accordion" data-type="accordion"> <!-- data-type values: accordion, toggle -->

                <!-- #1 accordion item -->
                <div class="acc__item">
                    <div class="acc__header">
                        <h2 class="acc__title">Is there a limit?</h2>
                        <div class="acc__icon"></div>
                    </div>
                    <div class="acc__content">
                        <p>There is no limit as long as you have the tokens.</p>

                    </div>
                </div>
                <!-- !#1 accordion item -->


            </div>
            <!-- !Accordion Shortcode -->

        </div>
    </div>


</div>
<!-- !FAQ Page -->
{% endblock %}

dashboard/templates/index-2.html
{% extends 'base.html' %}
{% load static %}
{% block title %}My Page{% endblock %}

{% block content %}
    <!-- Home Page -->
    <div class="chatPdf_fn_home">
        <div class="section_home">
            <div class="section_left">

                <!-- Title Shortcode -->
                <div class="chatPdf_fn_title_holder">
                    <h1 class="title">Unlock Your Imagination with ChatPDF</h1>
                    <p class="desc">Generate your ideas from pdf content</p>
                </div>
                <!-- !Title Shortcode -->

                <!-- Interactive List Shortcode -->
                <div class="chatPdf_fn_interactive_list modern">
                    <ul>
                        <li>
                            <div class="item">
                                <a href="{% url 'dashboard:chat' %}">
												<span class="icon">
													<img src="{% static 'svg/chat.svg' %}" alt="" class="fn__svg">
												</span>
                                    <h2 class="title">AI Chat Pdf</h2>
                                    <p class="desc"></p>
                                    <span class="arrow"><img src="{% static 'svg/arrow.svg' %}" alt="" class="fn__svg"></span>
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
                <!-- !Interactive List Shortcode -->

            </div>
            <div class="section_right">
                <div class="company_info">
{#                    <img src="{% static 'img/logo-desktop-full.png' %}" alt="">#}
                    <p class="fn__animated_text">"ChatPDF is your gateway to smarter document analysis. It's designed to empower users with advanced AI features, putting you in control of understanding your PDFs better."</p>
                    <hr>
                    <div class="fn__members">

                        <div class="active item">
                            <span class="circle"></span>
                            <span class="text">{{ user_count }} Members</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- !Home Page -->
{% endblock %}

dashboard/templates/notification-single.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Notifications-details{% endblock %}

{% block content %}
    <!-- Notification Single Page -->
    <div class="chatPdf_fn_notification_single_page">

        <!-- Page Title -->
        <div class="chatPdf_fn_pagetitle">
            <h2 class="title"><span>Notification:</span></h2>
        </div>
        <!-- !Page Title -->

        <div class="chatPdf_fn_notification_single_content">
            <div class="container small">
                <h1>{{ notification.message }}</h1>
                <p>{{ notification.details }}</p>

                <div class="fn__backto">
                    <a href="{% url 'dashboard:notifications' %}">
                        <img src="svg/arrow.svg" alt="" class="fn__svg">
                        <span class="text">Back to Notifications</span>
                    </a>
                </div>
            </div>
        </div>


    </div>
    <!-- !Notification Single Page -->
{% endblock %}

dashboard/templates/notifications.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Notifications{% endblock %}

{% block content %}
    <!-- Notifications Page -->
    <div class="chatPdf_fn_notifications_page">

        <!-- Page Title -->
        <div class="chatPdf_fn_pagetitle">
            <h2 class="title">Notifications</h2>
        </div>
        <!-- !Page Title -->

        <div class="chatPdf_fn_notifications_content">
            <div class="container small">


                <!-- Notifications List -->
                <div class="chatPdf_fn_notifications_list">
                    {% for notif in notifications %}
                    <div class="notification__item">
                        <a href="{% url 'dashboard:notfication_details' notif.id %}" class="fn__full_link"></a>
                        <h2 class="item__title">{{ notif.message }}</h2>
                        <span class="item__date">{{ notif.timestamp }}</span>
                    </div>
                    {% endfor %}

                </div>
                <!-- !Notifications List -->

            </div>
        </div>


    </div>
    <!-- !Notifications Page -->
{% endblock %}

dashboard/templates/privacy.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Privacy{% endblock %}

{% block content %}
<!-- privacy Page -->
<div class="chatPdf_fn_privacy_page">

    <!-- Page Title -->
    <div class="chatPdf_fn_pagetitle">
        <h2 class="title">Privacy Policy</h2>
    </div>
    <!-- !Page Title -->

    <div class="privacypage">
        <div class="container small">

            <h4 class="fn__animated_text">Who we are</h4>
            <p>Suggested text: Our website address is: https://frenify.com/work/envato/frenify/html/chatPdf/1/</p>
            <hr>

            <h4 class="fn__animated_text">Comments</h4>
            <p>Suggested text: When visitors leave comments on the site we collect the data shown in the comments form,
                and also the visitor’s IP address and browser user agent string to help spam detection.</p>
            <p>An anonymized string created from your email address (also called a hash) may be provided to the Gravatar
                service to see if you are using it. The Gravatar service privacy policy is available here:
                https://automattic.com/privacy/. After approval of your comment, your profile picture is visible to the
                public in the context of your comment.</p>
            <hr>

            <h4 class="fn__animated_text">Media</h4>
            <p>Suggested text: If you upload images to the website, you should avoid uploading images with embedded
                location data (EXIF GPS) included. Visitors to the website can download and extract any location data
                from images on the website.</p>
            <hr>

            <h4 class="fn__animated_text">Cookies</h4>
            <p>Suggested text: If you leave a comment on our site you may opt-in to saving your name, email address and
                website in cookies. These are for your convenience so that you do not have to fill in your details again
                when you leave another comment. These cookies will last for one year.</p>
            <p>If you visit our login page, we will set a temporary cookie to determine if your browser accepts cookies.
                This cookie contains no personal data and is discarded when you close your browser.</p>
            <p>When you log in, we will also set up several cookies to save your login information and your screen
                display choices. Login cookies last for two days, and screen options cookies last for a year. If you
                select "Remember Me", your login will persist for two weeks. If you log out of your account, the login
                cookies will be removed.</p>
            <p>If you edit or publish an article, an additional cookie will be saved in your browser. This cookie
                includes no personal data and simply indicates the post ID of the article you just edited. It expires
                after 1 day.</p>
            <hr>

            <h4 class="fn__animated_text">Embedded content from other websites</h4>
            <p>Suggested text: Articles on this site may include embedded content (e.g. videos, images, articles, etc.).
                Embedded content from other websites behaves in the exact same way as if the visitor has visited the
                other website.</p>
            <p>These websites may collect data about you, use cookies, embed additional third-party tracking, and
                monitor your interaction with that embedded content, including tracking your interaction with the
                embedded content if you have an account and are logged in to that website.</p>
            <hr>

            <h4 class="fn__animated_text">Who we share your data with</h4>
            <p>Suggested text: If you request a password reset, your IP address will be included in the reset email.</p>
        </div>
    </div>


</div>
<!-- !privacy Page -->

{% endblock %}

dashboard/templates/sign-in.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
  
<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<meta name="description" content="chatPdf">
<meta name="author" content="Henry">

<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<title>Sign In - chatPdf</title>


<script>
	if (!localStorage.hen_skin) {
		localStorage.hen_skin = 'dark';
	}
	if (!localStorage.chat) {
		localStorage.chat = '';
	}
	document.documentElement.setAttribute("data-chatPdf-skin", localStorage.hen_skin);
	if(localStorage.chat !== ''){
		document.documentElement.classList.add(localStorage.chat);
	}
  	
</script>

<!-- Google Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com/">
<link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@100;200;300;400;500;600;700;800;900&amp;family=Work+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap" rel="stylesheet">
<!-- !Google Fonts -->

<!-- Styles -->
<link type="text/css" rel="stylesheet" href="{% static 'css/plugins8a54.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'css/style8a54.css' %}" />
<!-- !Styles -->

</head>

<body>


<!-- Sign In -->
<div class="chatPdf_fn_sign">
	
	<div class="sign__content">
		<h1 class="logo">Designed by Henry</h1>
		<form class="login">
			<div class="form__content">
				<div class="form__title">Sign In</div>
				<div class="form__username">
					<label for="user_login">Username or Email</label>
					<input type="text" class="input" id="user_login" autocapitalize="off" autocomplete="username" aria-describedby="login-message">
				</div>
				<div class="form__pass">
					<div class="pass_lab">
						<label for="user_password">Password</label>
						<a href="#">Forget Password?</a>
					</div>
					<input type="password" id="user_password" autocomplete="current-password" spellcheck="false">
				</div>
				<div class="form__submit">
					<label class="fn__submit">
						<input type="submit" name="submit" value="Sign In">
					</label>
				</div>
				<div class="form__alternative">
					<div class="fn__lined_text">
						<div class="line"></div>
						<div class="text">Or</div>
						<div class="line"></div>
					</div>
					<a href="#" class="chatPdf_fn_button"><span>Sign in with Google</span></a>
				</div>
			</div>
		</form>
		<div class="sign__desc">
			<p>Not a member? <a href="sign-up.html">Sign Up</a></p>
		</div>
	</div>
	
</div>
<!-- !Sign In -->


<!-- Scripts -->
<script type="text/javascript" src="{% static 'js/jquery8a54.js' %}"></script>
<script type="text/javascript" src="{% static 'js/plugins8a54.js' %}"></script>
<!--[if lt IE 10]> <script type="text/javascript" src="{% static 'js/ie8.js' %}"></script> <![endif]-->
<script type="text/javascript" src="{% static 'js/init8a54.js' %}"></script>
<!-- !Scripts -->

</body>

</html>